pub const OPTIONS: &[&str] = &[
    "Archer",
    "Crossbowman",
    "Arbalester",
    "Skirmisher",
    "Elite Skirmisher",
    "Slinger",
    "Cavalry Archer",
    "Heavy Cavalry Archer",
    "Hand Cannoneer",
    "Elephant Archer",
    "Militia",
    "Man-at-Arms",
    "Long Swordsman",
    "Two-Handed Swordsman",
    "Champion",
    "Spearman",
    "Pikeman",
    "Halberdier",
    "Eagle Scout",
    "Eagle Warrior",
    "Elite Eagle Warrior",
    "Scout Cavalry",
    "Light Cavalry",
    "Hussar",
    "Knight",
    "Cavalier",
    "Paladin",
    "Camel Rider",
    "Heavy Camel Rider",
    "Battle Elephant",
    "Steppe Lancer",
    "Bloodlines",
    "Husbandry",
    "Thumb Ring",
    "Parthian Tactics",
    "Ballistics",
    "Chemistry",
    "Forging",
    "Iron Casting",
    "Blast Furnace",
    "Fletching",
    "Bodkin Arrow",
    "Bracer",
    "Plate Barding Armor",
    "Chain Barding Armor",
    "Scale Barding Armor",
    "Siege Engineers",
    "Squires",
    "Arson",
];